### Get All Adopters
GET localhost:8080/adopter
###

### Get Valid Adopter ID
GET localhost:8080/adopter/id=1
###

### Get InValid Adopter ID
GET localhost:8080/adopter/id=100
###

### Create Adopter
#POST localhost:8080/adopter?name=Fred Rubble&phoneNumber=123-456-7890&email=fred.rubble@email.com
POST localhost:8080/adopter
Content-Type: application/json

{
  "name": "Fred Rubble",
  "phoneNumber": "111-222-3333",
  "email": "fred.rubble@email.com"
}
###

### Create Invalid Adopter
#POST localhost:8080/adopter?name=Fred Rubble&phoneNumber=123-456-7890&email=fred.rubble@email.com
POST localhost:8080/adopter
Content-Type: application/json

{
  "name": "Barnie Rubble",
  "phoneNumber": "",
  "email": "barnie.rubble@email.com"
}

###

### Delete Valid ID
DELETE localhost:8080/adopter/id=4
###

### Delete Invaolid ID
DELETE localhost:8080/adopter/id=100
###