spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    name: adoption
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/postgres/schema.sql