spring:
  application:
    name: "AdoptionApp"
  profiles:
    active: "inmem"

---

spring:
  application:
    name: "AdoptionApp"
  profiles:
    active: "test-container"
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${TC_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    name: adoption
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/postgres/schema.sql

---

spring:
  application:
    name: "AdoptionApp"
  profiles:
    active: "prod"
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${PG_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    name: adoption
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/postgres/schema.sql
